name: Images legacy

on:
#  pull_request_target:
#    types:
#      - opened
#      - synchronize
#      - reopened
  push:
    branches:
      - master
      - pr/test-docker-images-legacy
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+

jobs:
  build-and-push:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - name: cilium
            dockerfile: ./Dockerfile
          - name: operator
            dockerfile: ./cilium-operator.Dockerfile
          - name: operator-aws
            dockerfile: ./cilium-operator-aws.Dockerfile
          - name: operator-azure
            dockerfile: ./cilium-operator-azure.Dockerfile
          - name: operator-generic
            dockerfile: ./cilium-operator-generic.Dockerfile
          - name: hubble-relay
            dockerfile: ./hubble-relay.Dockerfile
          - name: clustermesh-apiserver
            dockerfile: ./clustermesh-apiserver.Dockerfile
          - name: docker-plugin
            dockerfile: ./cilium-docker-plugin.Dockerfile
    steps:
      - name: Checkout PR
        if: ${{ github.repository == 'cilium/cilium' && github.event_name != 'pull_request_target' }}
        uses: actions/checkout@v2
      - name: Checkout Stable Branch
        if: ${{ github.repository == 'cilium/cilium' && github.event_name == 'pull_request_target' }}
        uses: actions/checkout@v2
        with:
         ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        # We only need DockerHub Login in releases and pushes to main branch
        if: ${{ github.repository == 'cilium/cilium' && github.event_name != 'pull_request_target' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Login to quay.io
        # We use different credentials for CI and for releases
        if: ${{ github.repository == 'cilium/cilium' && github.event_name != 'pull_request_target' }}
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Login to quay.io for CI
        # We use different credentials for CI and for releases
        if: ${{ github.repository == 'cilium/cilium' && github.event_name == 'pull_request_target' }}
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME_CI }}
          password: ${{ secrets.QUAY_PASSWORD_CI }}
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF##*/}
      - name: Release Builds ${{ matrix.name }}
        # We only need official DockerHub images in releases and pushes to main branch
        if: ${{ github.repository == 'cilium/cilium' && github.event_name != 'pull_request_target' }}
        uses: docker/build-push-action@v2
        id: docker_build_release
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          cache-from: ${{ github.repository_owner }}/${{ matrix.name }}-dev:cache-build-${{ steps.vars.outputs.tag }}
          cache-to: mode=max,type=registry,ref=${{ github.repository_owner }}/${{ matrix.name }}-dev:cache-build-${{ steps.vars.outputs.tag }}
          tags: |
            ${{ github.repository_owner }}/${{ matrix.name }}-dev:${{ steps.vars.outputs.tag }}
            quay.io/${{ github.repository_owner }}/${{ matrix.name }}-dev:${{ steps.vars.outputs.tag }}
            quay.io/${{ github.repository_owner }}/${{ matrix.name }}-ci:${{ github.sha }}
      - name: CI Builds ${{ matrix.name }}
        if: ${{ github.repository == 'cilium/cilium' && github.event_name == 'pull_request_target' }}
        uses: docker/build-push-action@v2
        id: docker_build_ci
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          cache-from: ${{ github.repository_owner }}/${{ matrix.name }}-dev:cache-build-${{ github.event.pull_request.head.ref }}
          tags: |
            quay.io/${{ github.repository_owner }}/${{ matrix.name }}-ci:${{ github.event.pull_request.head.sha }}
      - name: CI Image Releases digests
        if: ${{ github.repository == 'cilium/cilium' && github.event_name == 'pull_request_target' }}
        shell: bash
        run: |
          mkdir -p image-digest/
          echo "quay.io/${{ github.repository_owner }}/${{ matrix.name }}-ci:${{ github.sha }}@${{ steps.docker_build_ci.outputs.digest }}" > image-digest/${{ matrix.name }}.txt
      - name: Image Releases digests
        if: ${{ github.repository == 'cilium/cilium' && github.event_name != 'pull_request_target' }}
        shell: bash
        run: |
          mkdir -p image-digest/
          echo "docker.io/${{ github.repository_owner }}/${{ matrix.name }}-dev:${{ steps.vars.outputs.tag }}@${{ steps.docker_build_release.outputs.digest }}" > image-digest/${{ matrix.name }}.txt
          echo "quay.io/${{ github.repository_owner }}/${{ matrix.name }}-dev:${{ steps.vars.outputs.tag }}@${{ steps.docker_build_release.outputs.digest }}" >> image-digest/${{ matrix.name }}.txt
          echo "quay.io/${{ github.repository_owner }}/${{ matrix.name }}-ci:${{ github.sha }}@${{ steps.docker_build_release.outputs.digest }}" >> image-digest/${{ matrix.name }}.txt
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v2
        with:
          name: image-digest ${{ matrix.name }}
          path: image-digest
          retention-days: 1
  image-digests:
    name: Display Digests
    needs: build-and-push
    runs-on: ubuntu-20.04
    steps:
      - name: Image Releases digests
        if: ${{ github.repository == 'cilium/cilium' && github.event_name != 'pull_request_target' }}
        shell: bash
        run: |
          mkdir -p image-digest/
      - name: Download digests of all images built
        uses: actions/download-artifact@v2
        with:
          path: image-digest/

      - name: Image Digests
        shell: bash
        run: |
          cd image-digest/
          find -type f -exec cat {} \;
